### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Cooplix** [Cooplix/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by cooplix2** [comment]
— Hello! I am a student and I want to become very good backend developer. I like programming, algorithms and data structure. Highly motivated for learning new things.

**Comment by Cooplix** [comment]
EXPERIENCE

Imagination
TESLA
In a galaxy far, far away
New electric Walker "AT-AT" for Galactic Empire

2020
С-137
Helped create Portal Gun for budding scientist Rick Sanchez

2019
Provide Legal Exculpation And Sign Everything (P.L.E.A.S.E.)
New York


EDUCATION
MIT (Magicians Institute of Teaneck)
2015-2019
